# Generated by Django 4.2.10 on 2024-03-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_product_description_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
