# Generated by Django 4.2.10 on 2024-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employé', 'Employé'), ('Réparateur', 'Réparateur')], db_column='Rôle', default='Employé', max_length=100, verbose_name='Role'),
        ),
    ]
