# Generated by Django 4.2.10 on 2024-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_product_description_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employé', 'Employé')], db_column='Rôle', default='Employé', max_length=100, verbose_name='Role'),
        ),
    ]
