# Generated by Django 4.2.10 on 2024-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_column='Description', default='Pas de description'),
        ),
    ]
