# Generated by Django 4.2.10 on 2024-03-30 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_buying_price',
            field=models.PositiveIntegerField(blank=True, db_column="Prix d'achat initiale", null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_selling_price',
            field=models.PositiveIntegerField(blank=True, db_column='Prix de vente initiale', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='Nom', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_price',
            field=models.PositiveIntegerField(db_column="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(db_column='Quantité', validators=[django.core.validators.MinValueValidator(1, message='La quantité doit être supérieure à 0')]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(db_column='Quantité', validators=[django.core.validators.MinValueValidator(1, message='La quantité doit être supérieure à 0')]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_price',
            field=models.PositiveIntegerField(db_column='Prix de vente'),
        ),
    ]
