# Generated by Django 4.2.10 on 2024-05-02 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_repair_repair_price_repair_title_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareToRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Nom', max_length=100)),
                ('description', models.TextField(db_column='Description')),
                ('state', models.CharField(db_column='État', default='En réparation', max_length=20)),
            ],
            options={
                'db_table': 'MatérielAReparer',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_buying_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='product',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='repair_date',
        ),
        migrations.AddField(
            model_name='repair',
            name='delivery_date',
            field=models.DateField(blank=True, db_column='Date de remise', null=True),
        ),
        migrations.AddField(
            model_name='repair',
            name='deposit_date',
            field=models.DateField(auto_now_add=True, db_column='Date de dépôt', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_selling_price',
            field=models.PositiveIntegerField(db_column='Prix de vente initiale', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(db_column='Fournisseur', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.supplier'),
        ),
        migrations.AddField(
            model_name='repair',
            name='hardware',
            field=models.OneToOneField(db_column='Matériel', default=-1, on_delete=django.db.models.deletion.CASCADE, to='manager.hardwaretorepair'),
            preserve_default=False,
        ),
    ]
