# Generated by Django 4.2.10 on 2024-05-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_repair_prepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_price',
            field=models.PositiveIntegerField(blank=True, db_column="Prix d'achat", null=True),
        ),
        migrations.AlterModelTable(
            name='hardwaretorepair',
            table='MatérielARéparer',
        ),
    ]
