# Generated by Django 4.2.10 on 2024-05-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_purchaseorderitem_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.CreateModel(
            name='Suppliying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(db_column='Produit', on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
                ('supplier', models.ForeignKey(db_column='Fournisseur', on_delete=django.db.models.deletion.CASCADE, to='manager.supplier')),
            ],
            options={
                'db_table': 'Fournir',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(db_column='Fournisseurs', related_name='products', through='manager.Suppliying', to='manager.supplier'),
        ),
    ]
